version: '3'
services:
  mydb:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "bilbo"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432

volumes:
  postgres: {}

