{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bilbo-go.fullname" . -}}
{{- $namespace := .Values.namespace -}}
{{- $labels := include "bilbo-go.labels" . | indent 4 -}}

{{- range .Values.ingress.tls }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
{{ $labels }}
spec:
  secretName: {{ .secretName }}
  dnsNames:
  {{- range .hosts }}
    - {{ . | quote }}
  {{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingress: {{ $fullName }}
        domains:
        {{- range .hosts }}
          - {{ . | quote }}
        {{- end }}
---
{{- end }}
{{- end }}