apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: www-thebookofjoel-com
  namespace: thebookofjoel
spec:
  secretName: www-thebookofjoel-com-tls
  dnsNames:
    - www.thebookofjoel.com
    - thebookofjoel.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingress: ingress
        domains:
          - www.thebookofjoel.com
          - thebookofjoel.com