apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thebookofjoel
  namespace: thebookofjoel
spec:
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: thebookofjoel-main
    spec:
      initContainers:
        - name: migrations
          image: migrate-image
          command: ['/migrate']
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: db-host
                  key: db-host
            - name: POSTGRES_DBPORT
              valueFrom:
                secretKeyRef:
                  name: db-port
                  key: db-port
            - name: POSTGRES_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
            - name: POSTGRES_DBUSER
              value: gotest
            - name: POSTGRES_DBNAME
              value: gotest
          args: ['-source', 'file:///migrations/', '-database', 'postgres://$(POSTGRES_DBUSER):$(POSTGRES_DBPASSWORD)@$(POSTGRES_URL):$(POSTGRES_DBPORT)/$(POSTGRES_DBNAME)', 'up']
      containers:
        - name: backend
          image: backend
          ports:
            - containerPort: 8000
          env:
            - name: DEPLOYED
              value: "True"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: db-host
                  key: db-host
            - name: POSTGRES_DBPORT
              valueFrom:
                secretKeyRef:
                  name: db-port
                  key: db-port
            - name: POSTGRES_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
            - name: POSTGRES_DBUSER
              value: gotest
            - name: POSTGRES_DBNAME
              value: gotest
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
