apiVersion: apps/v1
kind: Deployment
metadata:
  name: thebookofjoel
  namespace: thebookofjoel
spec:
  selector:
    matchLabels:
      name: thebookofjoel-main
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: thebookofjoel-main
    spec:
      initContainers:
        - name: migrations
          image: migrate-image
          command: ['/migrate']
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: db-host-new
                  key: db-host
            - name: POSTGRES_DBPORT
              valueFrom:
                secretKeyRef:
                  name: db-port-new
                  key: db-port
            - name: POSTGRES_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-new
                  key: db-password
            - name: POSTGRES_DBUSER
              value: thebookofjoel-prod
            - name: POSTGRES_DBNAME
              value: thebookofjoel-prod
          args: ['-source', 'file:///migrations/', '-database', 'postgres://$(POSTGRES_DBUSER):$(POSTGRES_DBPASSWORD)@$(POSTGRES_URL):$(POSTGRES_DBPORT)/$(POSTGRES_DBNAME)', 'up']
      containers:
        - name: backend
          image: backend
          ports:
            - containerPort: 8000
          env:
            - name: DEPLOYED
              value: "True"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: db-host-new
                  key: db-host
            - name: POSTGRES_DBPORT
              valueFrom:
                secretKeyRef:
                  name: db-port-new
                  key: db-port
            - name: POSTGRES_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-new
                  key: db-password
            - name: POSTGRES_DBUSER
              value: thebookofjoel-prod
            - name: POSTGRES_DBNAME
              value: thebookofjoel-prod
        - name: nginx
          image: joelsaunders91/gothebookofjoel-nginx:46fcb4edce64cc2854d5321e0727b233bd978fcc
          ports:
            - containerPort: 80
