apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: thebookofjoel
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-host: "www.thebookofjoel.com"
    ingress.kubernetes.io/ssl-force-host: "true"
spec:
  tls:
    - secretName: www-thebookofjoel-com-tls
      hosts:
        - www.thebookofjoel.com
        - thebookofjoel.com
  rules:
    - host: www.thebookofjoel.com
      http:
        paths:
          - path: /api
            backend:
              serviceName: thebookofjoel-backend
              servicePort: 80
          - path: /
            backend:
              serviceName: thebookofjoel-nginx
              servicePort: 80
    - host: thebookofjoel.com
      http:
        paths:
          - path: /
            backend:
              serviceName: thebookofjoel-nginx
              servicePort: 80